name: Build, Push, and Deploy to GKE

on:
  push:
    branches:
      - week_7
  workflow_dispatch:

env:
  PROJECT_ID: mlops-501911
  GAR_LOCATION: us-central1
  GKE_CLUSTER: mlops-cluster
  GKE_ZONE: us-central1-a
  REPOSITORY: mlops-repo
  IMAGE: iris-app
  WORKLOAD_IDENTITY_PROVIDER: projects/588656205385/locations/global/workloadIdentityPools/github-pool/providers/github-provider
  SERVICE_ACCOUNT: gh-actions-sa@mlops-501911.iam.gserviceaccount.com

permissions:
  contents: read
  id-token: write

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # 1. Keyless Authentication via WIF
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    # 2. Login to Docker using the short-lived access token
    - name: Login to Artifact Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    # 3. Setup Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # 4. Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

    # 5. Connect to GKE Cluster
    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # 6. Deploy Manifests & Update Image
    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/
        kubectl set image deployment/iris-app-deployment iris-app=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}